AboutPage_Curtis
bscuron/bucketlist pull request #20
Opened 2023-04-14 18:08 UTC by CurtisLam

Re-adjusted footer display issue on web browser

2023-04-15 20:08 UTC, bscuron requested changes
Please see changes

2023-04-15 20:08 UTC, bscuron commented on src/screens/AboutScreen.tsx
> +                        </em>
<em> tag is not a react native tag

2023-04-15 20:08 UTC, bscuron commented on src/screens/AboutScreen.tsx
> +                        </em>
<em> tag is not a react native tag

2023-04-15 20:08 UTC, bscuron commented on src/screens/AboutScreen.tsx
> +                        </em>
<em> tag is not a react native tag

2023-04-15 20:08 UTC, bscuron commented on src/screens/AboutScreen.tsx
> +                </video>
<video> and <source> are not react native tags

2023-04-15 20:08 UTC, bscuron commented on src/screens/AboutScreen.tsx
> +
Invalid tags used

2023-04-16 17:43 UTC, CurtisLam reviewed
Removed imcompatible tag from about screen

2023-04-16 20:33 UTC, bscuron approved these changes

2023-04-16 20:33 UTC, merged